blog/urls.py
from django.urls import path
from .views import create_blog_post_view, category_view, tag_view, fav_update_view, post_edit_view

app_name = 'blog'

urlpatterns = [
    path('create/',create_blog_post_view, name='create_blog_post_view'),
    path('category/<slug:category_slug>/',category_view, name='category_view'),
    path('tag/<slug:tag_slug>/',tag_view, name='tag_view'),
    path('fav-update/',fav_update_view, name='fav_update_view'),
    path('post/<slug:post_slug>/edit/',post_edit_view, name='post_edit_view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from page.views import home_view

urlpatterns = [
    path('',home_view, name='home_view'),

    # BLOG
    path('blog/', include('blog.urls', namespace = 'blog')),

    # READ
    path('read/', include('read.urls', namespace = 'read')),

    # USER:
    path('user/', include('user_profile.urls', namespace = 'user')),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Third Party Apps:
from autoslug import AutoSlugField
from tinymce import models as tinymce_models

class CommonModel(models.Model):
    title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='title', unique=True, )
    is_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        abstract = True
        ordering = ('title',)

class Category(CommonModel):
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'blog:category_view',
            kwargs={
                "category_slug": self.slug
            }
        )


class Tag(CommonModel):
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'blog:tag_view',
            kwargs={
                "tag_slug": self.slug
            }
        )


class BlogPost(CommonModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    tag = models.ManyToManyField(Tag)
    cover_image = models.ImageField(upload_to='post')
    content = tinymce_models.HTMLField(blank=True, null=True)
    view_count = models.PositiveBigIntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-created_at',)
        
    def get_absolute_url(self):
        return reverse(
            'read:post_detail_view',
            kwargs={
                "user_slug": self.user.profile.slug,
                "post_slug": self.slug,
            }
        )
    
    def get_post_edit_url(self):
        return reverse(
            'blog:post_edit_view',
            kwargs={
                "post_slug": self.slug,
            }
        )
    
class UserPostFav(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

blog/forms.py
from django import forms
from django.core import validators
from tinymce.widgets import TinyMCE
from .models import BlogPost

# Our Validations
from config.denetimler import min_lenght_3

class BlogPostModelForm(forms.ModelForm):
    tag = forms.CharField(max_length=200)
    content = forms.CharField(widget=TinyMCE(attrs={'cols': 40,'rows': 20}))
    # title = forms.CharField(validators=[validators.MinLengthValidator(3, message="En az 3 karakter girmelisin..")])
    title = forms.CharField(validators=[min_lenght_3,])

    class Meta:
        model = BlogPost
        fields = [
            'title',
            'content',
            'category',
            'cover_image',
            'tag',
        ]

    # def clean_title(self):
    #     title = self.cleaned_data.get('title')
    #     if len(title) < 3:
    #         raise forms.ValidationError('Title bilgisi en az 3 karakterden oluşmalıdır..')
    #     return title.upper()

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages

import json

from .forms import BlogPostModelForm
from .models import Category, Tag, BlogPost, UserPostFav


@login_required(login_url='user:login_view')
def fav_update_view(request):
    if request.method == 'POST':
        post = get_object_or_404(BlogPost, slug=request.POST.get('slug'))
        if post:
            post_fav, created = UserPostFav.objects.get_or_create(
                user = request.user,
                post = post,
            )
            if not created:
                post_fav.is_deleted = not post_fav.is_deleted
                post_fav.save()
    return JsonResponse({'status': 200})

@login_required(login_url='user:login_view')
def create_blog_post_view(request):
    title = "Yeni Blog Post: "
    form = BlogPostModelForm()
    if request.method == 'POST':
        form = BlogPostModelForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            f = form.save(commit=False)
            print(form.cleaned_data)
            f.user = request.user
            f.save()
            tags = json.loads(form.cleaned_data.get('tag'))
            for item in tags:
                tag_item, created = Tag.objects.get_or_create(title=item.get('value').lower())
                tag_item.is_active = True
                tag_item.save()
                f.tag.add(tag_item)
            messages.success(request,'Blog Postunuz Başarıyla Oluşturuldu. Ana Sayfaya Yönlendiriliyorsunuz..')
            return redirect('home_view')
            
    context = dict(
        form=form,
        title=title,
    )
    return render(request, 'common_components/form.html', context)

def category_view(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    context = dict(
        category = category,
    )
    return render(request, 'blog/post_list.html', context)

@login_required(login_url='user:login_view')
def post_edit_view(request, post_slug):
    post = get_object_or_404(BlogPost, slug=post_slug)
    if not post.user == request.user:
        messages.warning(request, 'Bu Postu Düzenleyemezsiniz!')
        return redirect('home_view')
    title = post.title
    form = BlogPostModelForm(instance=post)

    if request.method == 'POST':
        form = BlogPostModelForm(request.POST or None, request.FILES or None, instance=post)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            tags = json.loads(form.cleaned_data.get('tag'))
            for item in tags:
                tag_item, created = Tag.objects.get_or_create(title=item.get('value').lower())
                tag_item.is_active = True
                tag_item.save()
                f.tag.add(tag_item)
            messages.success(request,'Blog Postunuz Başarıyla Düzenlendi..')
            return redirect('home_view')

    context = dict(
        title=title,
        form=form,
    )
    return render(request, 'common_components/form.html', context)


def tag_view(request, tag_slug):
    tag = get_object_or_404(Tag, slug=tag_slug)
    posts = BlogPost.objects.filter(tag=tag)
    context = dict(
        tag = tag,
    )
    return render(request, 'blog/post_list.html', context)

blog/templates/blog/create_blog_post.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/tagify.css' %}">
<div class="container mt-4">
    <div class="row">
        <div class="col-sm-8 offset-2">
            <h2>Yeni Blog Post</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                {{ form.media }}
                <button type="submit" class="btn btn-primary mt-3">Save</button>
            </form>
        </div>
    </div>
</div>

<script src="{% static 'js/tagify.polyfills.min.js' %}"></script>
<script src="{% static 'js/tagify.js' %}"></script>
<script>
    var input = document.querySelector('input[name=tag]');
    new Tagify(input)
</script>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-8 offset-sm-2 bg-light border mt-5 p-2">
            {% if category %}
            <h1>{{ category.title }}</h1>
            {% elif tag %}
            <h1>{{ tag.title }}</h1>
            {% elif favs %}
            <h1>{{ title }}</h1>
            {% endif %}
        </div>
        <div class="col-sm-8 offset-sm-2 mt-5">
            {% if category %}
                {% with posts=category.blogpost_set.all %}
                    {% for post in posts %}
                        {% include 'blog/components/post.html' %}
                    {% endfor %}
                {% endwith %}
            {% elif tag %}
                {% with posts=tag.blogpost_set.all %}
                    {% for post in posts %}
                        {% include 'blog/components/post.html' %}
                    {% endfor %}
                {% endwith %}
            {% elif favs %}
                {% with posts=favs %}
                    {% for post in posts %}
                        {% include 'blog/components/post.html' %}
                    {% endfor %}
                {% endwith %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}